# Generated by Django 6.0.5 on 2026-05-26 23:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("caption", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(upload_to=core.models.gallery_image_upload_to),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Gallery image",
                "verbose_name_plural": "Gallery images",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IndustryCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.models.industry_image_upload_to,
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(blank=True, default="Learn More", max_length=80),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Industry card",
                "verbose_name_plural": "Industry cards",
                "ordering": ["order", "title"],
            },
        ),
    ]
