# Generated by Django 5.2.16 on 2026-07-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_ledger', '0004_stocktransfer_issue_reported_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstock',
            name='location',
            field=models.CharField(blank=True, help_text='Physical rack location at this branch, e.g. C1R2. Set per-branch since the same product can sit in a different spot at each warehouse.', max_length=50),
        ),
    ]
