# Generated by Django 5.2.16 on 2026-07-29 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_unique_together_product_is_visible_and_more'),
        ('stock_ledger', '0005_branchstock_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingstock',
            name='product_name_snapshot',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='stockpurchase',
            name='product_name_snapshot',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='stocksale',
            name='product_name_snapshot',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='product_name_snapshot',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='openingstock',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_stock_entries', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stockpurchase',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_entries', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stocksale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_entries', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='products.product'),
        ),
        migrations.DeleteModel(
            name='OpeningStockImportBatch',
        ),
    ]
