# Generated by Django 5.2.16 on 2026-07-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_backfill_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Part/model code (e.g. 6001-ZZ). Identifies this product in the Stock Ledger and the Opening Stock Excel import.', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku', 'brand')},
        ),
    ]
