# Generated by Django 6.0.7 on 2026-08-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_unique_together_product_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Retail Price. Optional — leave blank for products without a published MRP.', max_digits=12, null=True, verbose_name='MRP'),
        ),
    ]
